openapi: 3.0.3
info:
  title: ReviewProcessLayer
  description: Process Layer that allows to add or read reviews
  version: 1.0.0
servers:
  - url: https://review-pl/api/v1
paths:
  /:
    get:
      summary: Retrieves review by id
      description: Allows the retrieval of reviews for a specific sitting spot
      operationId: retrieveReviews
      parameters:
        - name: sittingSpotId
          in: query
          description: unique id of the sitting spot
          required: true
          schema:
            $ref: '#/components/schemas/Review'

      responses:
        200:
          description: Operation succesful
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Review'
                  
        400:
          description: invalid input
          
        404:
          description: Id not found
    post:
      summary: Posts new reviews
      description: Posts a new review for an existing sitting spot
      operationId: postReview
      requestBody:
        content:
          application/json:
            schema:
              properties:
                sittingSpotId:
                  type: string
                  format: uuid
                review:
                  $ref: '#/components/schemas/Review'
        required: true
      responses:
        200:
          description: operation successful
        400:
          description: Invalid input
        404:
          description: id not found
                  
components:
  schemas:
    Review:
      properties:
        corpus:
          type: string
